version: '3.1'

services:
  app:
    image: node:20
    working_dir: /app/client
    volumes:
      - .:/app
    ports:
      - '${CLIENT_PORT}:${CLIENT_PORT}'
    command: sh -c "npm install && npm run dev"
    depends_on:
      - api
    env_file: .env

  api:
    image: node:20
    working_dir: /app/server
    volumes:
      - .:/app
    ports:
      - '${API_PORT}:${API_PORT}'
    command: sh -c "npm install && npm run dev"
    depends_on:
      - db
    env_file: .env

  db:
    image: postgres
    env_file: .env